{\rtf1\ansi\ansicpg1252\cocoartf2753
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # Generated by Django 4.2.3 on 2023-07-25 14:29\
\
from django.db import migrations, models\
\
\
class Migration(migrations.Migration):\
\
    initial = True\
\
    dependencies = [\
    ]\
\
    operations = [\
        migrations.CreateModel(\
            name='Booking',\
            fields=[\
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\
                ('name', models.CharField(max_length=255)),\
                ('no_of_guests', models.SmallIntegerField()),\
                ('reservation_date', models.DateField()),\
            ],\
        ),\
        migrations.CreateModel(\
            name='MenuItem',\
            fields=[\
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\
                ('title', models.CharField(max_length=255)),\
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),\
                ('inventory', models.SmallIntegerField()),\
            ],\
        ),\
    ]}